const LEVELS: Record<number, number> = {
  0: require("@/assets/levels/level-0.png"),
  1: require("@/assets/levels/level-1.png"),
  2: require("@/assets/levels/level-2.png"),
  3: require("@/assets/levels/level-3.png"),
  4: require("@/assets/levels/level-4.png"),
  5: require("@/assets/levels/level-5.png"),
  6: require("@/assets/levels/level-6.png"),
  7: require("@/assets/levels/level-7.png"),
  8: require("@/assets/levels/level-8.png"),
  9: require("@/assets/levels/level-9.png"),
  10: require("@/assets/levels/level-10.png"),
  11: require("@/assets/levels/level-11.png"),
  12: require("@/assets/levels/level-12.png"),
  13: require("@/assets/levels/level-13.png"),
  14: require("@/assets/levels/level-14.png"),
  15: require("@/assets/levels/level-15.png"),
  16: require("@/assets/levels/level-16.png"),
  17: require("@/assets/levels/level-17.png"),
  18: require("@/assets/levels/level-18.png"),
  19: require("@/assets/levels/level-19.png"),
  20: require("@/assets/levels/level-20.png"),
  21: require("@/assets/levels/level-21.png"),
  22: require("@/assets/levels/level-22.png"),
  23: require("@/assets/levels/level-23.png"),
  24: require("@/assets/levels/level-24.png"),
  25: require("@/assets/levels/level-25.png"),
  26: require("@/assets/levels/level-26.png"),
  27: require("@/assets/levels/level-27.png"),
  28: require("@/assets/levels/level-28.png"),
  29: require("@/assets/levels/level-29.png"),
  30: require("@/assets/levels/level-30.png"),
  31: require("@/assets/levels/level-31.png"),
  32: require("@/assets/levels/level-32.png"),
  33: require("@/assets/levels/level-33.png"),
  34: require("@/assets/levels/level-34.png"),
  35: require("@/assets/levels/level-35.png"),
  36: require("@/assets/levels/level-36.png"),
  37: require("@/assets/levels/level-37.png"),
  38: require("@/assets/levels/level-38.png"),
  39: require("@/assets/levels/level-39.png"),
  40: require("@/assets/levels/level-40.png"),
  41: require("@/assets/levels/level-41.png"),
  42: require("@/assets/levels/level-42.png"),
  43: require("@/assets/levels/level-43.png"),
  44: require("@/assets/levels/level-44.png"),
  45: require("@/assets/levels/level-45.png"),
  46: require("@/assets/levels/level-46.png"),
  47: require("@/assets/levels/level-47.png"),
  48: require("@/assets/levels/level-48.png"),
  49: require("@/assets/levels/level-49.png"),
  50: require("@/assets/levels/level-50.png"),
  51: require("@/assets/levels/level-51.png"),
  52: require("@/assets/levels/level-52.png"),
  53: require("@/assets/levels/level-53.png"),
  54: require("@/assets/levels/level-54.png"),
  55: require("@/assets/levels/level-55.png"),
  56: require("@/assets/levels/level-56.png"),
  57: require("@/assets/levels/level-57.png"),
  58: require("@/assets/levels/level-58.png"),
  59: require("@/assets/levels/level-59.png"),
  60: require("@/assets/levels/level-60.png"),
  61: require("@/assets/levels/level-61.png"),
  62: require("@/assets/levels/level-62.png"),
  63: require("@/assets/levels/level-63.png"),
  64: require("@/assets/levels/level-64.png"),
  65: require("@/assets/levels/level-65.png"),
  66: require("@/assets/levels/level-66.png"),
  67: require("@/assets/levels/level-67.png"),
  68: require("@/assets/levels/level-68.png"),
  69: require("@/assets/levels/level-69.png"),
  70: require("@/assets/levels/level-70.png"),
  71: require("@/assets/levels/level-71.png"),
  72: require("@/assets/levels/level-72.png"),
  73: require("@/assets/levels/level-73.png"),
  74: require("@/assets/levels/level-74.png"),
  75: require("@/assets/levels/level-75.png"),
  76: require("@/assets/levels/level-76.png"),
  77: require("@/assets/levels/level-77.png"),
  78: require("@/assets/levels/level-78.png"),
  79: require("@/assets/levels/level-79.png"),
  80: require("@/assets/levels/level-80.png"),
};

const TIERS: number[] = [
  require("@/assets/levels/tier-0.png"),
  require("@/assets/levels/tier-1.png"),
  require("@/assets/levels/tier-2.png"),
  require("@/assets/levels/tier-3.png"),
  require("@/assets/levels/tier-4.png"),
  require("@/assets/levels/tier-5.png"),
  require("@/assets/levels/tier-6.png"),
  require("@/assets/levels/tier-7.png"),
  require("@/assets/levels/tier-8.png"),
];

export function tierImage(tier: number): number {
  const idx = Math.max(0, Math.min(TIERS.length - 1, tier));
  return TIERS[idx];
}

export function levelImage(level: number, tier: number): number {
  return LEVELS[level] ?? tierImage(tier);
}
