uploads = []
outputs = []

[[generated]]
id = "kcWQK57EU2BoZ_-eCXpVJ"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-0.png"
type = "image"
title = "tier 0 skinny"

[[generated]]
id = "FkzWPKWHh7-SxifzKrQT8"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-1.png"
type = "image"
title = "tier 1 thin"

[[generated]]
id = "iKwCJDuB-GYUNXwBhSFe7"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-2.png"
type = "image"
title = "tier 2 average"

[[generated]]
id = "fGchluETm1asY3w7ok7A1"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-3.png"
type = "image"
title = "tier 3 toned"

[[generated]]
id = "qXJ2vC2ZkDCMU_jZItJ03"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-4.png"
type = "image"
title = "tier 4 fit"

[[generated]]
id = "mHymybFIAT6HCBJxHzP35"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-5.png"
type = "image"
title = "tier 5 strong"

[[generated]]
id = "IIU9oqNr1iuq7zvVTONOZ"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-6.png"
type = "image"
title = "tier 6 very muscular"

[[generated]]
id = "V5c5Tvi8Gru4uhFBFpxqk"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-7.png"
type = "image"
title = "tier 7 champion"

[[generated]]
id = "-a8JPVmVhgn8oqEvDE-F1"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-8.png"
type = "image"
title = "tier 8 legend"

[[generated]]
id = "H9YGdm4sHSKFP9RHM08JQ"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-9.png"
type = "image"
title = "level 9"

[[generated]]
id = "kXNCFIkt1u6ttdWsjZ1_q"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-1.png"
type = "image"
title = "level 1"

[[generated]]
id = "lWfoMJy_Rhyfqng1tQl9v"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-2.png"
type = "image"
title = "level 2"

[[generated]]
id = "aO6BPMR0HhltEW6Fp4Tja"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-3.png"
type = "image"
title = "level 3"

[[generated]]
id = "L78H87vx-W9Opv4fSMMUa"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-4.png"
type = "image"
title = "level 4"

[[generated]]
id = "2-IUk3O3qaZKP9FwGvReW"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-5.png"
type = "image"
title = "level 5"

[[generated]]
id = "2yJx_-FXBG4vTCOehA7oi"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-6.png"
type = "image"
title = "level 6"

[[generated]]
id = "xbjP_cEQZUU6lM4oLK941"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-7.png"
type = "image"
title = "level 7"

[[generated]]
id = "cjKO74X0KGvs9OnsvhWo6"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-8.png"
type = "image"
title = "level 8"

[[generated]]
id = "Yybqznri1vsVTX6OUsTOx"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-0.png"
type = "image"
title = "level 0 test"

[[generated]]
id = "kX77FQFkmAnP3BjoNayhg"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-10.png"
type = "image"
title = "lvl 10"

[[generated]]
id = "bAsEDDWsaRQ_G6y2GXoYD"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-11.png"
type = "image"
title = "lvl 11"

[[generated]]
id = "JHh2kx0m6R4wgvZ9Vtffm"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-12.png"
type = "image"
title = "lvl 12"

[[generated]]
id = "w8OfVbNwxutZMKE2VQ_m2"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-13.png"
type = "image"
title = "lvl 13"

[[generated]]
id = "isZHL9gcuPtxmFRUosFwr"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-14.png"
type = "image"
title = "lvl 14"

[[generated]]
id = "j4DQD4VPISfrqfDyX-fEu"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-15.png"
type = "image"
title = "lvl 15"

[[generated]]
id = "yV7qaXZEdp2d4OowSv_xy"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-16.png"
type = "image"
title = "lvl 16"

[[generated]]
id = "8hUkLnh0oNy8Os6VLASeu"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-17.png"
type = "image"
title = "lvl 17"

[[generated]]
id = "4t8nZy6-nizvdiN4KcK1T"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-18.png"
type = "image"
title = "lvl 18"

[[generated]]
id = "2HdEf8BlkFKfRG50v2shF"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-19.png"
type = "image"
title = "lvl 19"

[[generated]]
id = "m5Wj4q4OljxeNYoph0TTV"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-20.png"
type = "image"
title = "lvl 20"

[[generated]]
id = "pNC_qzLf0PJiaByBQvV7z"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-21.png"
type = "image"
title = "lvl 21"

[[generated]]
id = "I-rX2Z5Oxz-8vUn1Qn0yU"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-22.png"
type = "image"
title = "lvl 22"

[[generated]]
id = "ZTSbvukNjFEPjAndEuIw3"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-23.png"
type = "image"
title = "lvl 23"

[[generated]]
id = "O8aiWxkmGbVUtCRTEchqp"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-24.png"
type = "image"
title = "lvl 24"

[[generated]]
id = "M2MucynqJnM4M6npawUdc"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-25.png"
type = "image"
title = "lvl 25"

[[generated]]
id = "BfvH7UQ4qdW0v2RzNLl_s"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-26.png"
type = "image"
title = "lvl 26"

[[generated]]
id = "ftJCKbJcxdlQrxNbqe8Bl"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-27.png"
type = "image"
title = "lvl 27"

[[generated]]
id = "PVkcH_y-MniqIq6rKi4Hd"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-28.png"
type = "image"
title = "lvl 28"

[[generated]]
id = "WDcl9aqG4LJh3LE1OJsSU"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-29.png"
type = "image"
title = "lvl 29"

[[generated]]
id = "-O5PVFT674dAVX9csVUbM"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-30.png"
type = "image"
title = "lvl 30"

[[generated]]
id = "dk10xZArksQOvp6f2vc0W"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-31.png"
type = "image"
title = "lvl 31"

[[generated]]
id = "7ssvkmuYYhNMBuhiWSugQ"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-32.png"
type = "image"
title = "lvl 32"

[[generated]]
id = "1FK6gdkXLwt84J_nQARsR"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-33.png"
type = "image"
title = "lvl 33"

[[generated]]
id = "N_VgFHyxkbveAvzIchPgn"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-34.png"
type = "image"
title = "lvl 34"

[[generated]]
id = "wshcLa8QWoHHCb6FqfE34"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-35.png"
type = "image"
title = "lvl 35"

[[generated]]
id = "0eRgQGQfTO3b_2MR02Me0"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-36.png"
type = "image"
title = "lvl 36"

[[generated]]
id = "AVxh6r3lnIgt41w9_ZB9O"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-37.png"
type = "image"
title = "lvl 37"

[[generated]]
id = "hQLHIf2J23AvutFRhJO7D"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-38.png"
type = "image"
title = "lvl 38"

[[generated]]
id = "UeUBUktxQ1CAKRT9ovLXH"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-39.png"
type = "image"
title = "lvl 39"

[[generated]]
id = "b1RDt7qktoMvquz_KL8mv"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-40.png"
type = "image"
title = "lvl 40"

[[generated]]
id = "SVLZu1pvd1fRON67lqS4n"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-41.png"
type = "image"
title = "lvl 41"

[[generated]]
id = "v_xpA3F6f8mWcS3QznjSq"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-42.png"
type = "image"
title = "lvl 42"

[[generated]]
id = "VcNSYYFtKztrXRS75gte2"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-43.png"
type = "image"
title = "lvl 43"

[[generated]]
id = "X7zOIibasODjUUpZlt1vY"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-44.png"
type = "image"
title = "lvl 44"

[[generated]]
id = "ANn31QGDKHRPgnKStHC0_"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-45.png"
type = "image"
title = "lvl 45"

[[generated]]
id = "wT2x_CAE-ghQNFwSnFwXc"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-46.png"
type = "image"
title = "lvl 46"

[[generated]]
id = "uKSbfHiHx5p_uw4L2KZfy"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-47.png"
type = "image"
title = "lvl 47"

[[generated]]
id = "m468IX41sFkTAiw9QDtSA"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-48.png"
type = "image"
title = "lvl 48"

[[generated]]
id = "HnyLBq6gvWCsUfsOQRVKa"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-49.png"
type = "image"
title = "lvl 49"

[[generated]]
id = "EnH5kLaZDGuuoO5NqPsi4"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-50.png"
type = "image"
title = "lvl 50"

[[generated]]
id = "xFrSMw0KcKUbh5Py01k4h"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-51.png"
type = "image"
title = "lvl 51"

[[generated]]
id = "Fdsiqt4UrKXBp88vKD9h0"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-52.png"
type = "image"
title = "lvl 52"

[[generated]]
id = "pUsdALXeMP6L87EDQpjQD"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-53.png"
type = "image"
title = "lvl 53"

[[generated]]
id = "iQErvpqvPscK4q9jhKmTM"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-54.png"
type = "image"
title = "lvl 54"

[[generated]]
id = "9f15ojaIe2ujS-PWAzCgT"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-55.png"
type = "image"
title = "lvl 55"

[[generated]]
id = "Cs1rU_NK38TZa2abQE1su"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-56.png"
type = "image"
title = "lvl 56"

[[generated]]
id = "k8tbbxIMNwwOTfhRtkrrv"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-57.png"
type = "image"
title = "lvl 57"

[[generated]]
id = "DZ2V1QGywpRWTqYyVikmZ"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-58.png"
type = "image"
title = "lvl 58"

[[generated]]
id = "POQTx2AdU1v60stomm655"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-59.png"
type = "image"
title = "lvl 59"

[[generated]]
id = "dzuVArny33z8F58V_ZS2p"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-60.png"
type = "image"
title = "lvl 60"

[[generated]]
id = "gdBrna-aj-YOXvxSolkRJ"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-61.png"
type = "image"
title = "lvl 61"

[[generated]]
id = "Z8Vovf1l1YDOFQaBP9DLJ"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-62.png"
type = "image"
title = "lvl 62"

[[generated]]
id = "5UU9yXi4nvWLqLyylspCB"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-63.png"
type = "image"
title = "lvl 63"

[[generated]]
id = "obtgZadIFGV_NOICSWPf-"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-64.png"
type = "image"
title = "lvl 64"

[[generated]]
id = "P7MFMk6lHpUMcv_HJUs6r"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-65.png"
type = "image"
title = "lvl 65"

[[generated]]
id = "z9A4dUtdXm1ZSxT5ydQoS"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-66.png"
type = "image"
title = "lvl 66"

[[generated]]
id = "i4lmzb08Ex4uCaAKVth8A"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-67.png"
type = "image"
title = "lvl 67"

[[generated]]
id = "wGDBRae95qlraGskwZMnN"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-68.png"
type = "image"
title = "lvl 68"

[[generated]]
id = "CZpoUw6fvbuVCjoUM2Tcb"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-69.png"
type = "image"
title = "lvl 69"

[[generated]]
id = "yMUvtpzcDy50UaTfrySe7"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-70.png"
type = "image"
title = "lvl 70"

[[generated]]
id = "NDGCPG2v9QQ2hli5BBgdw"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-71.png"
type = "image"
title = "lvl 71"

[[generated]]
id = "7G0SNyAePDeEQAL_fLInu"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-72.png"
type = "image"
title = "lvl 72"

[[generated]]
id = "cQU2_lsY5rKvCuJFZcosd"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-73.png"
type = "image"
title = "lvl 73"

[[generated]]
id = "SJv0gxZyVXT2wJdvl6WPf"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-74.png"
type = "image"
title = "lvl 74"

[[generated]]
id = "3rozVQDi0TsPbP4e2hgFr"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-75.png"
type = "image"
title = "lvl 75"

[[generated]]
id = "nHYYMqBL4hAJ7WwUi43d0"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-76.png"
type = "image"
title = "lvl 76"

[[generated]]
id = "lG4t-88H4091698IohXGP"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-77.png"
type = "image"
title = "lvl 77"

[[generated]]
id = "5VQAiepFSE1IxdXcT-6Np"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-78.png"
type = "image"
title = "lvl 78"

[[generated]]
id = "yaroONoFGDlkIa5eu4UyV"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-79.png"
type = "image"
title = "lvl 79"

[[generated]]
id = "9gj5ZqYOXCbubdtEstNBf"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-80.png"
type = "image"
title = "lvl 80"

[[generated]]
id = "FKHHj6uqQUr-oukZkyy6o"
uri = "file://artifacts/gym-tracker-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-p0OwbufT1NEBko0QyzN2"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-0-f.png"
type = "image"
title = "tier 0 female fairy"

[[generated]]
id = "fE4KKxMF5E0V3g2DbJr4x"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-1-f.png"
type = "image"
title = "tier 1 female beginner"

[[generated]]
id = "8SN4HE56zdKKryYfCqTcY"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-2-f.png"
type = "image"
title = "tier 2 female starter"

[[generated]]
id = "eCCs9tABQSeiUFkI098_3"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-3-f.png"
type = "image"
title = "tier 3 female athletic"

[[generated]]
id = "b15UcvoHjc4LgRnAO8Fdj"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-4-f.png"
type = "image"
title = "tier 4 female action heroine"

[[generated]]
id = "rIidB_yzLSZCE6QVrhicz"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-5-f.png"
type = "image"
title = "tier 5 female warrior"

[[generated]]
id = "yeNzpi8W2wU_1Vqf5kZE0"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-6-f.png"
type = "image"
title = "tier 6 female bogatyr"

[[generated]]
id = "V29DGqQpVMGowv26q-QB_"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-7-f.png"
type = "image"
title = "tier 7 female valkyrie champion"

[[generated]]
id = "q_AbX-ogjUp1yUiH20sKP"
uri = "file://artifacts/gym-tracker/src/assets/levels/tier-8-f.png"
type = "image"
title = "tier 8 female legend goddess"

[[generated]]
id = "P8TMVqoVDzoWDjlaM6hyQ"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-0-f.png"
type = "image"
title = "level 0 fairy feechka"

[[generated]]
id = "YWOUYXWcmqq3wc8a2WX8m"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-1-f.png"
type = "image"
title = "level 1 thumbelina"

[[generated]]
id = "Pnj8OT3aUYRPIG59xUf1x"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-2-f.png"
type = "image"
title = "level 2 malvina"

[[generated]]
id = "a7_z7zq06NiKFbvtcYbs4"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-18-f.png"
type = "image"
title = "level 18 pippi"

[[generated]]
id = "8-Si4GTUjAKlFw4VsinC0"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-38-f.png"
type = "image"
title = "level 38 katniss"

[[generated]]
id = "ETTbW8u6DBtTsMpVs-wi0"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-46-f.png"
type = "image"
title = "level 46 black widow"

[[generated]]
id = "SA7ri02yLJObQIp-o3UPe"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-54-f.png"
type = "image"
title = "level 54 polyanitsa"

[[generated]]
id = "T5aMCCE5uDCxxpuaFg9vq"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-60-f.png"
type = "image"
title = "level 60 xena warrior queen"

[[generated]]
id = "Gb2cTzdNKwYQGac2Iwulm"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-59-f.png"
type = "image"
title = "level 59 joan of arc"

[[generated]]
id = "FNUYJ5QhlIGbAabVR-VhD"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-63-f.png"
type = "image"
title = "level 63 valkyrie"

[[generated]]
id = "IbHjKiI4Um--Ns3dwDHOS"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-65-f.png"
type = "image"
title = "level 65 wonder woman diana"

[[generated]]
id = "PUpO148wYNaXAVAYqlHyn"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-77-f.png"
type = "image"
title = "level 77 artemis goddess"

[[generated]]
id = "b9IxmMfztb_PNu8dljh1j"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-80-f.png"
type = "image"
title = "level 80 female legend"

[[generated]]
id = "XCAjnHb0zh5k4DRZe4Ovj"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-10-f.png"
type = "image"
title = "level 10 snegurochka"

[[generated]]
id = "rt95iDEaPEmttKJV0lp6d"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-11-f.png"
type = "image"
title = "level 11 gerda snow queen"

[[generated]]
id = "hcPdXHBzUqw5ULmnAk1ek"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-19-f.png"
type = "image"
title = "level 19 mary poppins"

[[generated]]
id = "5BAAbvVcIp9KhvvEMgtgl"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-45-f.png"
type = "image"
title = "level 45 rey desert warrior"

[[generated]]
id = "_Wk6e6XMlttYt8IhGxKej"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-3-f.png"
type = "image"
title = "level 3 humble young girl barbell"

[[generated]]
id = "On9pX_CE5XpITJ_JXt056"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-31-f.png"
type = "image"
title = "level 31 red hair archer warrior"

[[generated]]
id = "C50j-olleA-RMO0miWwKu"
uri = "file://artifacts/gym-tracker/src/assets/levels/level-32-f.png"
type = "image"
title = "level 32 asian female warrior sword"
